Models/Tvshow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ShowReel.Models
{
    public class Tvshow
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Rating { get; set; }
        public string Image { get; set; }
        public int Year { get; set; }

        public int EpisodeGuideID { get; set; }
        

        }
    
}

Controllers/TVShowsController.cs
using ShowReel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace ShowReel.Controllers
{
    public class TVShowsController : Controller
    {
        // GET: TVShows
        ShowReelDB _db = new ShowReelDB();
        [HttpGet]
        public ActionResult TVshow(String action = null, String type = null, String keyword = null)
        {

            if (type == "popularity")
            {
                var model =
                    _db.Tvshows
                    .OrderByDescending(r => r.Rating)
                    .Where(r => keyword == null || r.Name.StartsWith(keyword));
                return View(model);
            }
            else if (type == "premiereYear" )
            {

                var model = 
                    _db.Tvshows
                    .OrderBy(r => r.Year)
                    .Where(r => keyword == null || r.Name.StartsWith(keyword));
                return View(model);
            }
            else {
                var model =
                _db.Tvshows
                .OrderByDescending(r=>r.Name)
                .Where(r=> keyword == null || r.Name.StartsWith(keyword));
                return View(model);
            }
            
             
            
        }

      

        // GET: TVShows/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TVShows/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TVShows/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TVShows/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TVShows/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TVShows/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: TVShows/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

      

        protected override void Dispose(bool disposing)
        {
            if (_db != null) {

                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TVShows/TVshow.cshtml
@model IEnumerable<ShowReel.Models.Tvshow>
@{
    ViewBag.Title = "TVshow";
}

<div class="filter line-under--gray">
    <form method="get" action="@Url.Action("TVshow", "TVShows")">
        <div class="input-container">
            <label class="search-label"><i class="fa fa-search"></i></label>
            <input type="search" name="keyword" id="search" class="input-search" />
            <button type="submit" id="submit" value="Search" class="btn-submit"><i class="fa fa-chevron-right"></i></button>
        </div>
        <div class="filter-items-container">
            <div class="dropdown">
                <button type="button" class="btn btn-dropdown dropdown-toggle txt--uppercase w--medium" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Genre <i class="fa fa-angle-down"></i></button>
                <ul class="dropdown-menu">
                    <li name="action" id="action"><a href="#">Action</a></li>
                    <li name="action" id="drama"><a href="#">Drama</a></li>
                    <li name="action" id="fantasy"><a href="#">Fantasy</a></li>
                    <li name="action" id="sci-fi"><a href="#">Sci-fi</a></li>
                    <li name="action" id="mistery"><a href="#">Mistery</a></li>
                </ul>
            </div>

            <div class="radio-container">
                <div class="radio-group">
                    <input type="radio" name="type" id="radio-1" value="premiereYear">
                    <label for="radio-1">Year of Premiere</label>
                </div>
                <div class="radio-group">
                    <input type="radio" name="type" id="radio-2" value="popularity">
                    <label for="radio-2">Popularity</label>
                </div>
                <div class="radio-group">
                    <input type="radio" name="type" id="radio-3" value="all">
                    <label for="radio-3">All</label>
                </div>
            </div>
        </div>
    </form>
</div>

@foreach (var item in Model)
{

    <div class="row flex line-under--gray normal">
    <div class="col-md-4 image-container">
        <div class="listed-item__img" style="background:url(../Content/Images/@item.Image) no-repeat center; background-size: cover;"></div>
    </div>
    <div class="col-md-8 flex--column">

        <h2 class="show-title line-under left"> @item.Name<span style="font-size:medium;"> @item.Year</span></h2>
        <div class="rating">
            @{
                var k = (int)Math.Round(@item.Rating);
                for (int i = 0; i < k; i++)
                {
                    <i class="fa fa-star"></i>
                }
                for (int i = k; i < 10; i++)
                {
                    <i class="fa fa-star-o"></i>
                }
            }
        </div>
        <p class="show-description">  @item.Description</p>
        <a href="#" class="btn btn--red-inverse btn-track @item.Id">Track</a>


        <script>
            $(".@item.Id").click(function () {
                $(this).text(function (i, text) {
                    return text === "Track" ? "Untrack" : "Track";
                })
            });
        </script>

    </div>

        
</div>
}